volumes:
  dynamodb-local-data:

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:2.5.4"
    container_name: dynamodb-local
    user: root
    ports:
      - "8000:8000"
    volumes:
      - "dynamodb-local-data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
