[package]
name = "aoc_leaderbot_lib"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

readme = "README.md"
license.workspace = true

homepage = "https://github.com/clechasseur/aoc_leaderbot/tree/main/aoc_leaderbot_lib#readme"
repository.workspace = true
documentation = "https://docs.rs/aoc_leaderbot_lib/"

description = "Support library for aoc_leaderbot, an Advent of Code leaderboard-watching bot"

keywords = [ "aoc", "advent-of-code" ]
categories = [ "asynchronous" ]

include = [ "src/**/*", "tests/**/*", "LICENSE", "README.md" ]

[package.metadata.docs.rs]
all-features = true
targets = [ "x86_64-unknown-linux-gnu" ]
rustc-args = [ "--cfg", "docsrs" ]

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [ "cfg(tarpaulin)", "cfg(tarpaulin_include)", "cfg(coverage)", "cfg(coverage_nightly)" ]

[features]
default = ["config-env"]

config-mem = ["dep:derive_builder", "dep:veil"]
config-env = ["config-mem"]

storage-mem = []

[dependencies]
anyhow = { workspace = true }
aoc_leaderboard = { workspace = true, features = ["http"] }
chrono = { workspace = true }
derive_builder = { workspace = true, optional = true }
gratte = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }
veil = { workspace = true, optional = true }

[dev-dependencies]
aoc_leaderboard = { workspace = true, features = ["__test_helpers"] }
assert_matches = { workspace = true }
mockall = { workspace = true }
reqwest = { workspace = true }
rstest = { workspace = true }
serial_test = { workspace = true }
test-log = { workspace = true, default-features = false, features = ["trace"] }
tokio = { workspace = true, features = ["macros"] }
uuid = { workspace = true, features = ["v4"] }
