[dependencies]
lazy_static = "1.5.0"
regex = "1.11.1"
rustls = "0.23.23"
tower = "0.4.13"
tracing-subscriber = "0.3.19"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.11.1"
security-framework-sys = "2.14.0"
